version: '3'
services:
  notebook:
    container_name: shift-python-conda-5.2.0
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/notebooks
    build:
      context: .
      dockerfile: Dockerfile
